### ISSUE TITLE
No projects listed when whitelist is empty

### ISSUE THREAD

**Issue by XanderXAJ** [mehcode/atom-project-plus#21]
I'm using Atom 1.6.0-beta7 on Windows.  I recently upgraded to Project Plus 0.7, and found all my projects had disappeared!

On a hunch I added `~` to the whitelist, and the projects within the home directory are now listed.  To have everything showing, I'll need to add each drive (C:\, D:).  Good ol' Windows...

Would you agree that if the whitelist is empty, no whitelist behaviour should occur?

**Comment by mehcode** [comment]
> Would you agree that if the whitelist is empty, no whitelist behaviour should occur?

Definitely. This is a bug.

@shemerey ?

**Comment by mehcode** [comment]
@XanderXAJ I can't reproduce this. If you can reproduce this again, can you open the developer tools `View -> Developer -> Toggle Developer Tools` and run `atom.config.get("project-plus.folderWhitelist")` and `atom.config.get("project-plus.folderBlacklist")` in the console?

**Comment by XanderXAJ** [comment]
Sure thing.  I cleared the whitelist config, ensured the issue was reproduced, then ran the following:

```
atom.config.get("project-plus.folderWhitelist")
""
atom.config.get("project-plus.folderBlacklist")
""
```

**Comment by shemerey** [comment]
@XanderXAJ @mehcode I don't have windows, but it looks like a `bug` will install `Windows` in VM and check this out, fix should simple :)

**Comment by mehcode** [comment]
If not I can test this on Windows (didn't even think about the OS; heh) at work tomorrow. I have Windows 10 on another partition.

**Comment by shemerey** [comment]
@mehcode @XanderXAJ yes it's defiantly a bug, `minimatch` doesn't recognize `" "` on `Windows` properly

**Comment by mehcode** [comment]
@XanderXAJ Please update to 0.7.2 and let us know if this is still a problem.

**Comment by XanderXAJ** [comment]
Thanks @mehcode @shemerey, I'm now getting all projects listed! :)

If this is a problem with `minimatch`, consider raising an upstream bug?

**Comment by mehcode** [comment]
We were essentially doing this:

```
minimatch.filter('{,/**,}')("project/path")
```

... for each path in your project. If the whitelist was an empty string. If I was the maintainer of minimatch I'd tell us to fix our usage. It's an odd thing that it didn't error on linux; it doesn't even look valid.

**Comment by XanderXAJ** [comment]
Fair enough!  I hadn't gotten around to looking at the underlying code.  Thanks for the explanation — and the fix!
