### ISSUE TITLE
[Noob Question] How do i save a project?

### ISSUE THREAD

**Issue by webcaetano** [mehcode/atom-project-plus#25]
Hello guys. 
Awesome job. 

How do i save an project? :cry:

**Comment by shemerey** [comment]
@webcaetano  what do you mean by `save` ? It works with any project what have ever been opened by Atom.

**Comment by webcaetano** [comment]
@shemerey that answer the question.  :tada: 
Thanks.

I had an fresh atom installed....open only one project... and it shows empty , then i got lost. 

I was only waiting this feature to come out on atom to i migrate to it.

**Comment by mehcode** [comment]
@webcaetano Also note that you can use `Ctrl-Shift-P` (command menu) to execute the `Project Plus: Open` command to switch to a new project by selecting one or more folders on the file system.
