### ISSUE TITLE
does not work since atom 1.6

### ISSUE THREAD

**Issue by frederic-joventures** [mehcode/atom-project-plus#26]
Since 1.6 I have this error 

> Scopes at Cursor
> source.terraform
> comment.double-slash{quote}

**Comment by mehcode** [comment]
Any chance you got a red box and can hit the create issue button on it?

**Comment by frederic-joventures** [comment]
actually it is working now. Strange because I had the error on all my computers.
I will close it for now.
Tx for the quick response
