### ISSUE TITLE
Remove blacklist and rename the whitelist config to make it more visible

### ISSUE THREAD

**Issue by mehcode** [mehcode/atom-project-plus#29]
@shemerey 

More on blacklist in specific. As I talk to people that use this package, I find that nobody uses blacklist and everybody either uses whitelist or wants to use it (and doesn't understand that it is what it is). 
- [x] Remove blacklist
- [x] Rename whitelist to `Project Home` (or similar/better name) with a slightly adjusted description.

**Comment by shemerey** [comment]
@mehcode agreed. Will take a look

**Comment by mehcode** [comment]
Awesome. We just need the rename now. :+1:
