### ISSUE TITLE
Reading projects out of projects.cson not working

### ISSUE THREAD

**Issue by gee-forr** [mehcode/atom-project-plus#43]
Hey,

So, the latest patch fixes the exception, but I can't seem to get the project switcher to list any projects... I've checked my projects.cson file, and it's getting populated, but when I cmd+ctrl+p, I get an empty list with a status of 'No saved projects'.

Let me know if I can give you any debug info at all.

**Comment by gee-forr** [comment]
Howdy,

Just thought I'd give you a little more data:

I'm using Atom 1.7.1 and Project Plus 0.8.2

PP config:

```
  "project-plus":
    autoDiscover: false
    projectHome: "/Users/gabrielf/projects/"
    showPath: true
```

projects.cson:

```
"crystal-web-portal":
  title: "crystal-web-portal"
  paths: [
    "/Users/gabrielf/Projects/crystal_web/crystal-web-portal"
  ]
"vast-client-portal":
  title: "vast-client-portal"
  paths: [
    "/Users/gabrielf/Projects/VAST/vast-client-portal"
  ]
"isdsl.rb":
  title: "isdsl.rb"
  paths: [
    "/Users/gabrielf/Projects/Zero One/isdsl.rb"
  ]
"service-view":
  title: "service-view"
  paths: [
    "/Users/gabrielf/Projects/IS/service-view"
  ]
tad:
  title: "tad"
  paths: [
    "/Users/gabrielf/Projects/talented_africa/tad"
  ]
```

**Comment by mehcode** [comment]
Can you try renaming your project home to `/Users/gabrielf/Projects/` ?

**Comment by gee-forr** [comment]
Hey, that fixed it. Sorry, really dumb of me. I've issued PR #44 just to make it clear to any potential future users that have this issue.

Thanks for the help dude.
