### ISSUE TITLE
Clear auto-discover cache

### ISSUE THREAD

**Issue by gnestor** [mehcode/atom-project-plus#49]
To reproduce: Rename or delete a project/git repo that is being auto-discovered by project-plus

Result: The deleted project still lingers in auto-discover list or the old name of the renamed project still lingers in the auto-discover list

**Comment by mehcode** [comment]
`CTRL-ALT-P` -> `Project Plus: Remove` -> Hit enter on the selection you want to remove.

**Comment by gnestor** [comment]
@mehcode I tried this and it doesn't remove the project... 🤔

**Comment by mehcode** [comment]
@gnestor I had the command sequence wrong: https://github.com/mehcode/atom-project-plus/issues/50#issuecomment-223356520

Does that still not fix it?

**Comment by gnestor** [comment]
Ya I tried `COMMAND PALLETTE` > `Project Plus: Remove` > `ENTER` on project and it still show up in the projects list.

**Comment by mehcode** [comment]
Really odd. I can't reproduce this. 
- Try clearing atom storage (the old pre-1.7 one) `rm -rf $HOME/.atom/storage` ? 
- Try running `Project Plus: Edit Projects` and see if its sticking in there for some reason?
- `atom --clear-window-state` will clear atom's session cache (which should wipe out project-plus cache as well)

**Comment by gnestor** [comment]
`atom --clear-window-state` cleared all of my projects. Now I just see the 2 that I've been working in today. This resolves my issue but how do I re-populate my auto-discovered projects?

**Comment by mehcode** [comment]
> [...] This resolves my issue but how do I re-populate my auto-discovered projects?

I apologize if I wasn't clear. That clear command wipes the state permanently. You'll need to rebuild it by manually re-opening your projects or putting them in the projects.cson.
