### ISSUE TITLE
Remove a project from the project-plus list

### ISSUE THREAD

**Issue by Grazouillis** [mehcode/atom-project-plus#50]
Hello,

I inadvertently created a project which contains two folders (different projects) with atom.

When I remove the project folders from the left sidebar, this one project stays in the list when I I activate the keybinding 'CTRL+ALT+P'.

![ee](https://cloud.githubusercontent.com/assets/8795284/15738964/1cf00fac-28ae-11e6-8e47-c5afb4699348.PNG)

Do you have an idea to solve my problem ?
Thank you !

**Comment by mehcode** [comment]
`CTRL-ALT-P` -> `Project Plus: Remove` -> Hit enter on the selection you want to remove.

**Comment by Grazouillis** [comment]
Do you mean CTRL ALT P, right-clic on "delete" in the contextual menu ?
It doesn't work, I suppose that it isn't it.
Sorry, mehcode :/

![sans titre 1](https://cloud.githubusercontent.com/assets/8795284/15742657/9c6925ea-28c0-11e6-96c3-fa9fb70ad4ac.png)

Where do I find "Project Plus: Remove" there ?

**Comment by mehcode** [comment]
Oh. I'm sorry. I meant `Ctrl-Shift-P` -- There is a `project-plus:remove` command in this package. That will open up the project finder but enter will remove the project rather than open it.

**Comment by Grazouillis** [comment]
Haaaaaaaaaaa ! :) Nice.
A thousand thanks !
