### ISSUE TITLE
Projects saved but don't always appear in the list.

### ISSUE THREAD

**Issue by trusktr** [mehcode/atom-project-plus#52]
Here's a screenshot showing the `projects.cson` file. In the shot we see I'm looking for "mighty" and nothing appears in the list after typing "mighty".

![screen shot 2016-06-12 at 9 51 08 am](https://cloud.githubusercontent.com/assets/297678/15992541/9b033ee6-3083-11e6-8a24-0a7b2ac561c2.png)

**Comment by mehcode** [comment]
@trusktr Currently the project home setting acts as a filter for the project finder. This issue makes me thing projects explicitly defined in projects.cson should show up regardless of the filter setting. Thoughts?

//cc @shemerey

**Comment by shemerey** [comment]
yes, I think listed project has to be shown regardless `project home` option

**Comment by mehcode** [comment]
Agreed.
