### ISSUE TITLE
Packages enable/disable?

### ISSUE THREAD

**Issue by polarathene** [mehcode/atom-project-plus#53]
I'm not sure if this is a feature suitable for this package, if you know of an existing one that would compliment this package or request please let me know as searching for one is difficult due to keywords used.

I'd like to enable/disable packages per project or project type(based on files). This should avoid loading of packages not required for certain projects(language/environment focused packages that have no relevance in the active project). A good example might be switching between IDE packages, doing React development, use Nuclide, Arduino use Platform.io, not working on a project that would use these IDE packages, none are enabled. 

Currently I have to manually change these when switching between projects, would be great to have it as part of project specific settings. Even if it's just a whitelist/blacklist of some packages to enable/disable.

**Comment by shemerey** [comment]
@polarathene Here is some links that can be helpful 
- https://discuss.atom.io/t/project-specific-configurations/8407
- https://discuss.atom.io/t/layered-configuration/9373

You can participate in this discussion as well https://discuss.atom.io/t/layered-configuration/9373
