### ISSUE TITLE
Project Discovery is slow

### ISSUE THREAD

**Issue by wottpal** [mehcode/atom-project-plus#55]
Hey,
in the settings I've disabled to look for projects outside of the `projects.cson` and even though I have less than ten projects in there it always takes up to 2secs of `Discovering projects..` when I toggle project-plus menu. Is this considered as normal behavior? are the results cached in any way?

Regards from Germany, 
Dennis

**Comment by willdawsonme** [comment]
Is this still an issue @dkerzig?

**Comment by wottpal** [comment]
Sorry, can not confirm this. Stopped using this package.

**Comment by willdawsonme** [comment]
Alrighty, I'll close this and if anyone experiences something similar, please create a new issue.
