### ISSUE TITLE
How to delete old projects ?

### ISSUE THREAD

**Issue by valter-silva-au** [mehcode/atom-project-plus#56]
Hi, I worked with several projects, which I don't want to show up anymore when I tried to switch between projects. Is it possible to delete these entries ?

Thank you!

**Comment by willdawsonme** [comment]
@valterhenrique There's a menu item (`Project Plus: Remove`) which will bring up the project finder view. Selecting any project from there will remove it!

**Comment by mehcode** [comment]
Thanks @willdawsonme 

@valterhenrique Please re-open if that doesn't work.

**Comment by valter-silva-au** [comment]
Perfect! Thanks a lot @willdawsonme and @mehcode! 
For those with the same problem, just press CTRL+SHIFT+P on Atom, and then search for Project Plus: Remove and select the project that you want to remove from it!

**Comment by marbin65** [comment]
I am a beginner and i have some projects in my Recents Project list that i want to delete. But i dont find a posibility to do this. Please can someone help me !?
I dont find the  menu item (Project Plus: Remove) !!
