### ISSUE TITLE
Broken with atom 1.9.3

### ISSUE THREAD

**Issue by airtonix** [mehcode/atom-project-plus#62]
flushed, cleared, wiped and committed all kinds of deep inside genocide action on my atom install.

Plugin still broken. stuck on  "Discovering projects" regardless of the command i use.

**Comment by willdawsonme** [comment]
@airtonix Can you try again with 1.9.4?

**Comment by willdawsonme** [comment]
@airtonix I'll close this for now. If it's still happening on the latest Atom (now 1.9.8), please re-open.
