### ISSUE TITLE
Utilize alternate scoring engine (fuzzaldrin-plus)

### ISSUE THREAD

**Issue by mehcode** [mehcode/atom-project-plus#7]

**Comment by chuckhendo** [comment]
Would also be great to have the fuzzy search include the path name (at a much lower priority than the name). I was just researching integration of fuzzaldrin-plus into project quick open, so I can tackle this if you haven't already started on it @mehcode

**Comment by chuckhendo** [comment]
It would also be nice to highlight in bold (or a darker font color or something) the characters that match the search. I could also look into adding this

**Comment by mehcode** [comment]
@chuckhendo :clap: Awesome. I haven't started this at all. We should assign issues to ourselves so we don't step on toes. The issue list on here is just me shooting out ideas. If I start on something I was marking it as in-progress but the assignment works better with multiple people.

**Comment by chuckhendo** [comment]
Can't seem to assign to myself; assuming because I'm not a contributor

**Comment by mehcode** [comment]
Fixed that :cake:

**Comment by chuckhendo** [comment]
Awesome! Should be able to take a look at it this weekend

**Comment by jeancroy** [comment]
> Would also be great to have the fuzzy search include the path name (at a much lower priority than the name). 

Yeah fuzzaldrin api wasn't designed to support multiple search field. But I seen that request popup at a few place so I may add it. Will probably support weighting the fields too.
