### ISSUE TITLE
Support for Terminal Plus

### ISSUE THREAD

**Issue by sebszocinski** [mehcode/atom-project-plus#72]
Hi, Any chance we can get support for [Terminal Plus](https://atom.io/packages/terminal-plus) so that terminal tabs are closed and re-opened to the new working dir?

**Comment by willdawsonme** [comment]
@rockethouse I actually find it quite useful that terminal-plus tabs stay open when switching projects! Any new tabs will open to the newly activated directory, but existing ones stay open, which is necessary for a long-running process like a node server.

I'm also not 100% sure that it's possible from our end, and it seems more likely that terminal plus would have to subscribe to a project activation event.

**Comment by sebszocinski** [comment]
ah okay fair enough, that makes sense. Cheers for the response!
