### ISSUE TITLE
Add ability to remove/archive projects

### ISSUE THREAD

**Issue by mehcode** [mehcode/atom-project-plus#9]

**Comment by nixpulvis** [comment]
I don't find myself needing to do this that often, but it's a feature I could _really_ use. I hate clutter.

**Comment by psifertex** [comment]
Was this closed resolved or wontfix? I was subscribed as well because my project list has some screwy stuff in it I'd like to cleanup.

**Comment by mehcode** [comment]
@psifertex This was added to v9.0
