### ISSUE TITLE
Deprecate in favor of project manager

### ISSUE THREAD

**Issue by mehcode** [mehcode/atom-project-plus#95]
A lot of time has past and Project Manager (what I based this project on) now has most of the functionality of this package (including usage of atom-project-util which contains the project in-window switch by myself).

I'm seeing tons of issues crop up of this package not working for various reasons and while it still happily works on my machine (insert amusing "works here" comment) I'm not seeing a reason to not officially deprecate this package.

Thoughts?

If you're actively using this package, would you see if [project-manager](https://github.com/danielbrodin/atom-project-manager) can satisfy how you use project-plus ?

**Comment by vinyll** [comment]
Indeed I had not seen how much progress the Project Manager's settings had done.
I guess it does pretty much everything Project Plus does and has much more users.
Thanks for all the work done on this plugin and for the Atom users! ❤️

**Comment by jeffjarchow** [comment]
I thought the empty tree problem was something wrong in project-plus, so I switched to project-manager today to see if the empty tree problem was fixed and it was not. Seems to be an atom thing. But in doing so I see how much progress has been made on project-manager. It seems to fulfill all the needs of a project management package.

It looks like project-plus may not be needed with all of the functionality that is in project-manager. Thank you for all the great work on project-plus.

**Comment by vinyll** [comment]
Same feeling here. However I downgraded back to 1.16 due to this bug.
(If you stick with 1.17, note that a workaround is to open the project in a new window (Shift+enter))

**Comment by daverogers** [comment]
Agreed. I now use Project Manager. Thank you :)

**Comment by mehcode** [comment]
Going to close this issues in favor of https://github.com/danielbrodin/atom-project-manager/issues/345
